package com.retail.dolphinpos.data.mapper

import com.retail.dolphinpos.data.entities.category.CategoryEntity
import com.retail.dolphinpos.data.entities.products.ProductImagesEntity
import com.retail.dolphinpos.data.entities.products.ProductsEntity
import com.retail.dolphinpos.data.entities.products.VariantImagesEntity
import com.retail.dolphinpos.data.entities.products.VariantsEntity
import com.retail.dolphinpos.data.entities.products.VendorEntity
import com.google.gson.Gson
import com.retail.dolphinpos.domain.model.home.catrgories_products.CategoryData
import com.retail.dolphinpos.domain.model.home.catrgories_products.ProductImage
import com.retail.dolphinpos.domain.model.home.catrgories_products.Products
import com.retail.dolphinpos.domain.model.home.catrgories_products.Variant
import com.retail.dolphinpos.domain.model.home.catrgories_products.VariantImage
import com.retail.dolphinpos.domain.model.home.catrgories_products.Vendor
import com.retail.dolphinpos.domain.model.product.CreateProductRequest
import com.retail.dolphinpos.domain.model.product.ProductVariantRequest

object ProductMapper {

    // -------------------------
    // Domain → Entity Mappers
    // -------------------------

    fun toCategoryEntity(category: CategoryData): CategoryEntity {
        return CategoryEntity(
            id = category.id,
            title = category.title,
            description = category.description,
            productCount = category.productCount
        )
    }

    fun toProductEntity(products: Products, categoryId: Int, storeId: Int, locationId: Int): ProductsEntity {
        val gson = Gson()
        // Convert secondaryBarcodes list to JSON string
        val secondaryBarCodesJson = products.secondaryBarcodes?.let { barcodes ->
            if (barcodes.isNotEmpty()) {
                val barcodeStrings = barcodes.mapNotNull { it.secondaryBarCode }
                if (barcodeStrings.isNotEmpty()) {
                    gson.toJson(barcodeStrings)
                } else null
            } else null
        } ?: null
        
        return ProductsEntity(
            id = 0, // Will be auto-generated by Room
            serverId = products.id, // Store server ID in serverId field
            categoryId = categoryId,
            name = products.name,
            sku = products.sku,
            description = products.description,
            quantity = products.quantity,
            status = products.status,
            cashPrice = products.cashPrice,
            cardPrice = products.cardPrice,
            barCode = products.barCode,
            plu = products.plu,
            storeId = storeId,
            locationId = locationId,
            chargeTaxOnThisProduct = products.chargeTaxOnThisProduct,
            cardTax = products.cardTax,
            cashTax = products.cashTax,
            price = products.price,
            compareAtPrice = products.compareAtPrice,
            costPrice = products.costPrice,
            secondaryBarCodes = secondaryBarCodesJson,
            trackQuantity = products.trackQuantity,
            continueSellingWhenOutOfStock = products.continueSellingWhenOutOfStock == true,
            isEBTEligible = products.isEBTEligible,
            isIDRequired = products.isIDRequired
        )
    }

    fun toProductImagesEntity(productImages: ProductImage, productId: Int): ProductImagesEntity {
        return ProductImagesEntity(
            productId = productId,
            fileURL = productImages.fileURL,
            originalName = productImages.originalName
        )
    }

    fun toProductVariantsEntity(variants: Variant, productId: Int): VariantsEntity {
        return VariantsEntity(
            id = 0, // Will be auto-generated by Room
            serverId = variants.id, // Store server ID in serverId field
            productId = productId,
            cardPrice = variants.cardPrice,
            cashPrice = variants.cashPrice,
            price = variants.price,
            quantity = variants.quantity,
            title = variants.title,
            sku = variants.sku,
            plu = variants.plu,
            barCode = variants.barCode
        )
    }

    fun toVariantImagesEntity(variantImages: VariantImage, variantId: Int): VariantImagesEntity {
        return VariantImagesEntity(
            variantId = variantId,
            fileURL = variantImages.fileURL,
            originalName = variantImages.originalName
        )
    }

    fun toProductVendorEntity(vendor: Vendor, productId: Int): VendorEntity {
        return VendorEntity(
            id = vendor.id,
            productId = productId,
            title = vendor.title
        )
    }

    // -------------------------
    // Entity → Domain Mappers
    // -------------------------

    fun toCategory(
        categoryEntity: List<CategoryEntity>,
    ): List<CategoryData> {
        return categoryEntity.map { category ->
            CategoryData(
                id = category.id,
                title = category.title,
                description = category.description,
                productCount = category.productCount,
                products = emptyList()
            )
        }
    }

    fun toProducts(
        productsEntity: List<ProductsEntity>,
    ): List<Products> {
        return productsEntity.map { product ->
            Products(
                id = product.serverId ?: product.id,
                categoryId = product.categoryId,
                storeId = product.storeId,
                name = product.name,
                description = product.description,
                quantity = product.quantity,
                status = product.status,
                cashPrice = product.cashPrice,
                cardPrice = product.cardPrice,
                barCode = product.barCode,
                plu = product.plu,
                locationId = product.locationId,
                chargeTaxOnThisProduct = product.chargeTaxOnThisProduct,
                vendor = null,
                variants = emptyList(),
                images = emptyList(),
                secondaryBarcodes = null,
                cardTax = product.cardTax,
                cashTax = product.cashTax
            )
        }
    }

    fun toProduct(
        productEntity: ProductsEntity,
        productImages: List<ProductImagesEntity>,
        variants: List<VariantsEntity>,
        variantImagesMap: Map<Int, List<VariantImagesEntity>> = emptyMap(),
        gson: Gson? = null
    ): Products {
        val variantImagesList = variants.map { variant ->
            val images = variantImagesMap[variant.id]?.map { toVariantImage(it) } ?: emptyList()
            toVariant(variant, images)
        }
        
        // Parse secondaryBarcodes from JSON string
        val secondaryBarcodesList = productEntity.secondaryBarCodes?.let { jsonString ->
            try {
                if (gson != null) {
                    val type = object : com.google.gson.reflect.TypeToken<List<String>>() {}.type
                    val barcodeStrings = gson.fromJson<List<String>>(jsonString, type)
                    barcodeStrings.mapIndexed { index, barcode ->
                        com.retail.dolphinpos.domain.model.home.catrgories_products.SecondaryBarcode(
                            id = index,
                            secondaryBarCode = barcode
                        )
                    }
                } else {
                    emptyList<com.retail.dolphinpos.domain.model.home.catrgories_products.SecondaryBarcode>()
                }
            } catch (e: Exception) {
                emptyList<com.retail.dolphinpos.domain.model.home.catrgories_products.SecondaryBarcode>()
            }
        } ?: emptyList<com.retail.dolphinpos.domain.model.home.catrgories_products.SecondaryBarcode>()
        
        return Products(
            id = productEntity.serverId ?: productEntity.id,
            categoryId = productEntity.categoryId,
            storeId = productEntity.storeId,
            name = productEntity.name,
            description = productEntity.description,
            quantity = productEntity.quantity,
            status = productEntity.status,
            cashPrice = productEntity.cashPrice,
            cardPrice = productEntity.cardPrice,
            barCode = productEntity.barCode,
            plu = productEntity.plu,
            locationId = productEntity.locationId,
            chargeTaxOnThisProduct = productEntity.chargeTaxOnThisProduct,
            vendor = null,
            variants = variantImagesList,
            images = productImages.map { toProductImage(it) },
            secondaryBarcodes = secondaryBarcodesList,
            cardTax = productEntity.cardTax,
            cashTax = productEntity.cashTax,
            isEBTEligible = productEntity.isEBTEligible,
            trackQuantity = productEntity.trackQuantity,
            continueSellingWhenOutOfStock = productEntity.continueSellingWhenOutOfStock,
            price = productEntity.price,
            compareAtPrice = productEntity.compareAtPrice,
            costPrice = productEntity.costPrice
        )
    }

    fun toProductImage(productImagesEntity: ProductImagesEntity): ProductImage {
        return ProductImage(
            fileURL = productImagesEntity.fileURL,
            originalName = productImagesEntity.originalName
        )
    }


    fun toVariant(variantsEntity: VariantsEntity): Variant {
        return Variant(
            id = variantsEntity.serverId ?: variantsEntity.id,
            title = variantsEntity.title,
            price = variantsEntity.price,
            quantity = variantsEntity.quantity,
            sku = variantsEntity.sku,
            plu = variantsEntity.plu,
            cardPrice = variantsEntity.cardPrice,
            cashPrice = variantsEntity.cashPrice,
            barCode = variantsEntity.barCode,
            attributes = null,
            images = emptyList()
        )
    }

    fun toVariant(variantsEntity: VariantsEntity, variantImages: List<VariantImage>): Variant {
        return Variant(
            id = variantsEntity.serverId ?: variantsEntity.id,
            title = variantsEntity.title,
            price = variantsEntity.price,
            quantity = variantsEntity.quantity,
            sku = variantsEntity.sku,
            plu = variantsEntity.plu,
            cardPrice = variantsEntity.cardPrice,
            cashPrice = variantsEntity.cashPrice,
            barCode = variantsEntity.barCode,
            attributes = null,
            images = variantImages
        )
    }

    fun toVariantImage(variantImagesEntity: VariantImagesEntity): VariantImage {
        return VariantImage(
            fileURL = variantImagesEntity.fileURL,
            originalName = variantImagesEntity.originalName
        )
    }

    fun toVendor(vendorEntity: VendorEntity): Vendor {
        return Vendor(
            id = vendorEntity.id,
            title = vendorEntity.title
        )
    }

    // -------------------------
    // CreateProductRequest → Entity Mappers
    // -------------------------

    fun toProductEntityFromRequest(request: CreateProductRequest): ProductsEntity {
        val gson = Gson()
        return ProductsEntity(
            id = 0, // Will be auto-generated
            serverId = null,
            categoryId = request.categoryId,
            storeId = request.storeId,
            name = request.name,
            description = request.description,
            quantity = request.quantity,
            status = request.status,
            cashPrice = request.cashPrice ?: request.price ?: "0.00",
            cardPrice = request.cardPrice ?: request.price ?: "0.00",
            price = request.price,
            compareAtPrice = null, // Can be added if needed
            costPrice = request.costPrice,
            barCode = request.barCode,
            plu = request.plu,
            sku = request.sku,
            secondaryBarCodes = if (request.secondaryBarCodes.isEmpty()) null else gson.toJson(request.secondaryBarCodes),
            chargeTaxOnThisProduct = true, // Default
            locationId = request.locationId,
            cardTax = 0.0,
            cashTax = 0.0,
            trackQuantity = request.trackQuantity,
            continueSellingWhenOutOfStock = request.continueSellingWhenOutOfStock,
            productVendorId = request.productVendorId,
            currentVendorId = request.currentVendorId,
            salesChannel = if (request.salesChannel.isEmpty()) null else gson.toJson(request.salesChannel),
            shippingWeight = request.shippingWeight,
            shippingWeightUnit = request.shippingWeightUnit,
            isPhysicalProduct = request.isPhysicalProduct,
            customsInformation = request.customsInformation,
            isEBTEligible = false, // Can be added to request if needed
            isIDRequired = false, // Can be added to request if needed
            isSynced = false, // Not synced yet
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )
    }

    fun toVariantEntityFromRequest(
        variant: ProductVariantRequest,
        productId: Int,
        gson: Gson
    ): VariantsEntity {
        return VariantsEntity(
            id = 0, // Will be auto-generated
            serverId = null,
            productId = productId,
            cardPrice = variant.cardPrice ?: variant.price,
            cashPrice = variant.cashPrice ?: variant.price,
            price = variant.price,
            costPrice = variant.costPrice,
            quantity = variant.quantity,
            sku = variant.sku,
            plu = null, // PLU not available in ProductVariantRequest yet
            title = variant.title,
            barCode = variant.barCode,
            locationId = variant.locationId,
            isSynced = false, // Not synced yet
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )
    }

    // -------------------------
    // Entity → CreateProductRequest Mappers
    // -------------------------

    fun toCreateProductRequest(
        product: ProductsEntity,
        productImages: List<ProductImagesEntity>,
        variants: List<VariantsEntity>,
        variantImagesMap: Map<Int, List<VariantImagesEntity>> = emptyMap(),
        gson: Gson
    ): CreateProductRequest {
        return CreateProductRequest(
            name = product.name ?: "",
            description = product.description ?: "",
            images = productImages.map { image ->
                com.retail.dolphinpos.domain.model.product.ProductImageRequest(
                    fileURL = image.fileURL ?: "",
                    originalName = image.originalName ?: ""
                )
            },
            status = product.status ?: "active",
            price = product.price,
            costPrice = product.costPrice,
            trackQuantity = product.trackQuantity,
            quantity = product.quantity,
            continueSellingWhenOutOfStock = product.continueSellingWhenOutOfStock,
            salesChannel = product.salesChannel?.let { 
                val type = object : com.google.gson.reflect.TypeToken<List<String>>() {}.type
                gson.fromJson<List<String>>(it, type)
            } ?: emptyList(),
            productVendorId = product.productVendorId,
            currentVendorId = product.currentVendorId,
            categoryId = product.categoryId,
            storeId = product.storeId,
            locationId = product.locationId,
            shippingWeight = product.shippingWeight,
            shippingWeightUnit = product.shippingWeightUnit,
            isPhysicalProduct = product.isPhysicalProduct,
            customsInformation = product.customsInformation,
            barCode = product.barCode,
            secondaryBarCodes = product.secondaryBarCodes?.let { 
                val type = object : com.google.gson.reflect.TypeToken<List<String>>() {}.type
                gson.fromJson<List<String>>(it, type)
            } ?: emptyList(),
            sku = product.sku,
            plu = product.plu,
            //varients = emptyMap(), // Can be derived from variants if needed
            cashPrice = product.cashPrice,
            cardPrice = product.cardPrice,
            variants = variants.map { variant ->
                val variantImages = variantImagesMap[variant.id]?.map { imageEntity ->
                    com.retail.dolphinpos.domain.model.product.ProductImageRequest(
                        fileURL = imageEntity.fileURL ?: "",
                        originalName = imageEntity.originalName ?: ""
                    )
                } ?: emptyList()
                
                ProductVariantRequest(
                    title = variant.title ?: "",
                    price = variant.price,
                    costPrice = variant.costPrice,
                    quantity = variant.quantity,
                    barCode = variant.barCode,
                    sku = variant.sku,
                    cashPrice = variant.cashPrice,
                    cardPrice = variant.cardPrice,
                    locationId = variant.locationId ?: product.locationId,
                    images = variantImages.ifEmpty { null }
                )
            }
        )
    }

}