package com.retail.dolphinpos.data.entities.user

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.UUID

/**
 * Batch entity representing a POS batch.
 * 
 * CRITICAL DESIGN DECISIONS:
 * - Uses UUID as primary key (batchId) generated locally on POS
 * - Batch IDs are ALWAYS generated by POS, never by server/backend
 * - lifecycleStatus tracks business state (OPEN/CLOSED)
 * - syncStatus tracks server sync state (START_PENDING → START_SYNCED → CLOSE_PENDING → CLOSE_SYNCED)
 * - Only one batch can be OPEN at a time per register
 */
@Entity(tableName = "batch")
data class BatchEntity(
    /**
     * Primary key: UUID generated locally on device (POS always generates batch IDs)
     * This ensures uniqueness even when offline and allows safe retries (idempotent)
     * Backend does not assign batch IDs - they are always generated by POS
     */
    @PrimaryKey
    val batchId: String = UUID.randomUUID().toString(),
    
    /**
     * Human-readable batch number (generated locally on POS)
     */
    val batchNo: String,
    
    val userId: Int?,
    val storeId: Int?,
    val registerId: Int?,
    val locationId: Int?,
    
    /**
     * Starting cash amount when batch was opened
     */
    val startingCashAmount: Double,
    
    /**
     * Timestamp when batch was opened (locally)
     */
    val openedAt: Long = System.currentTimeMillis(),
    
    /**
     * Timestamp when batch was closed (null = open batch)
     */
    val closedAt: Long? = null,
    
    /**
     * Closing cash amount when batch was closed
     */
    val closingCashAmount: Double? = null,
    
    /**
     * Batch lifecycle status (business state)
     */
    val lifecycleStatus: BatchLifecycleStatus = BatchLifecycleStatus.OPEN,
    
    /**
     * Batch sync status (server sync state)
     */
    val syncStatus: BatchSyncStatus = BatchSyncStatus.START_PENDING,
    
    /**
     * Deprecated: Use lifecycleStatus and syncStatus instead
     * Kept for backward compatibility during migration
     */
    val startedAt: Long = System.currentTimeMillis(),
    
    /**
     * Deprecated: Use syncStatus instead
     * Kept for backward compatibility during migration
     */
    val isSynced: Boolean = false
) {
    /**
     * Returns true if this batch is currently open (lifecycle status)
     */
    fun isOpen(): Boolean = lifecycleStatus == BatchLifecycleStatus.OPEN
    
    /**
     * Returns true if orders for this batch can be synced.
     * Orders can only be synced if batch start is synced (START_SYNCED or later).
     */
    fun canSyncOrders(): Boolean {
        return syncStatus == BatchSyncStatus.START_SYNCED ||
               syncStatus == BatchSyncStatus.CLOSE_PENDING ||
               syncStatus == BatchSyncStatus.CLOSE_SYNCED
    }
}
